---
- name: Pull Docker Image and Deploy It
  hosts: localhost
  become: true
  vars:
        ansible_python_interpreter: /usr/bin/python3
  tasks:
          - name: Ensure that Docker service is enabled
            service:
                    name: docker
                    state: started

          - name: Pull the Docker Image
            docker_image:
                    name: shubhanshu1902/calculatorapp:latest
                    source: pull

          - name: Run the Container
            shell: docker run -it -d shubhanshu1902/calculatorapp