---
- name: Pull Docker Image and Deploy It
  hosts: localhost
  vars:
          ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_method: sudo
  tasks:
          - name: Ensure that Docker service is enabled
            service:
                    name: docker
                    state: started

          - name: Pull the Docker Image
            docker_image:
                    name: shubhanshu1902/calculatorapp
                    source: pull

          - name: Run the Container
            shell: docker run -it -d rshubhanshu1902/calculatorapp